name: 05 - filters activity types
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Running whenever a PR is opened or synchronized"
