name: 09 - functions

on:
  push:
  workflow_dispatch:

env:
  personal_var: 'my name is start with my'
  my: 'my'

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 10
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{success()}}
        run: echo "Hello, world!"
      - name: I will execute
        if: ${{failure()}}
        run: echo "failure!"
      - name: I will execute
        if: ${{!cancelled()}}
        run: echo "not cancelled!"
      - name: I will not execute
        if: ${{cancelled()}}
        run: echo "cancelled!"
      - name: some step
        run: '${{startsWith(env.personal_var, env.my)}}'
      - name: labels
        run: ${{toJson(github.event_name)}}
