name: 10 - controlling the execution flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: Run unit tests
        default: true

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running linting and building"
  unit-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "Running tests..."
      - if: ${{!inputs.pass-unit-tests}}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-test
    steps:
      - run: echo "Deploying to nonprod"
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - run: echo "Running e2e tests"
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - run: echo "Running load tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-tests
      - load-tests
    steps:
      - run: echo "Running linting and building"
