name: 11 - working with inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: skip deployment
        default: false
        type: boolean
      # target:
      #   type: environment
      #   description: target environment
      #   required: true
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{!inputs.dry-run}}
    steps:
      - name: deploy
        run: echo "deploying to prod"
