name: 11 - working with inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: skip deployment
        required: false
        default: false
        type: boolean
      target:
        description: target environment
        required: true
        type: environment
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{!inputs.dry-run}}
    environment: ${{inputs.target}}
    steps:
      - name: deploy
        run: echo "deploying to ${{inputs.target}}"
